# ----------------------------------------------------------------------------
# GitHub Actions workflow to test building all code samples.
#
# See docs:
# - https://castle-engine.io/github_actions
# - https://docs.github.com/en/actions
# ----------------------------------------------------------------------------

name: Test Code Samples

on: [push, pull_request]

# Necessary to have && working in Windows jobs
defaults:
  run:
    shell: bash

jobs:
  build-using-docker:
    name: Test Code Samples with FPC 3.3.1
    runs-on: ubuntu-latest
    # Using FPC 3.3.1, as some examples (anonymous functions, some generics)
    # require it, FPC 3.2.0 is not enough.
    container: kambi/castle-engine-cloud-builds-tools:cge-none-fpc331
    steps:
    - uses: actions/checkout@v5
    - run: cd code-samples/ && make

  delphi_test:
    name: Delphi
    strategy:
      matrix:
        host-label: [
          delphi_12
        ]
    runs-on: ${{ matrix.host-label }}
    steps:
      - uses: actions/checkout@v5
      - name: Delphi Build (Win32)
        run: cd code-samples/ && make all-delphi-win32
      - name: Delphi Build (Win64)
        run: cd code-samples/ && make all-delphi-win64
